name: dsmpy 
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pytest
  - numpy=1.22.3
  - mpi4py
  - matplotlib
  - pandas
  - geographiclib
  - obspy
  - clang
  - gfortran
  - conda-build
