name: dsmpy 
dependencies:
  - python
  - pytest
  - numpy
  - mpi4py
  - matplotlib
  - pandas
  - conda-forge::geographiclib
  - conda-forge::obspy
  - conda-forge::c-compiler
  - conda-forge::fortran-compiler
  - cartopy
