[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "mypy",
    "wheel",
    'obspy',
    'mpi4py',
    'pandas',
    'matplotlib',
    'geographiclib',
    "numpy",
]
build-backend = 'setuptools.build_meta'
