{% set name = "dsmpy" %}
{% set version = "1.0a4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/afeborgeaud/dsmpy/releases/download/v1.0a4/dsmpy-1.0a4.tar.gz"

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('clang') }}
    - {{ compiler('fortran') }}
    - numpy
  host:
    - {{ compiler('clang') }}
    - {{ compiler('fortran') }}
    - openmpi >=4.1,<4.2.0a0
    - geographiclib
    - matplotlib
    - mpi4py
    - numpy
    - obspy
    - pandas
    - pip
    - python
  run:
    - openmpi >=4.1,<4.2.0a0
    - geographiclib
    - matplotlib
    - mpi4py
    - numpy
    - obspy
    - pandas
    - python

test:
  imports:
    - dsmpy
    - dsmpy.resources
    - dsmpy.spc
    - dsmpy.utils

about:
  home: "https://github.com/afeborgeaud/dsmpy"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Python wrapper for DSM"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - afeborgeaud
